import Head from "next/head";
import Container from "react-bootstrap/Container";
import AppGuides from "@/components/AppGuides";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import ExampleComponents from "@/components/ExampleComponents";

import { Col, Row } from "react-bootstrap";
import Sidebar from "@/components/Sidebar/Sidebar";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bootstrap w/ React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container as="main" fluid>
        <Row>
          <Sidebar />
          <Col md={6} className="main-content">
            <Header />

            <h1>Build Bootstrap with React</h1>

            <ExampleComponents />

            <hr className="col-1 my-5 mx-0" />

            <AppGuides />
            {/* <AppGuides /> */}
            <Footer />
          </Col>
        </Row>
      </Container>
    </>
  );
}
